const A1_wordlist = [
    {word: 'about', translate: ''}, {word: 'above', translate: ''}, {word: 'address', translate: ''},
    {word: 'adult', translate: ''}, {word: 'after', translate: ''}, {word: 'afternoon', translate: ''},
    {word: 'again', translate: ''}, {word: 'age', translate: ''}, {word: 'all', translate: ''},
    {word: 'all right', translate: ''}, {word: 'alright', translate: ''}, {word: 'also', translate: ''},
    {word: 'always', translate: ''}, {word: 'a.m', translate: ''}, {word: 'an', translate: ''},
    {word: 'and', translate: ''}, {word: 'animal', translate: ''}, {word: 'answer', translate: ''},
    {word: 'any', translate: ''}, {word: 'anything', translate: ''}, {word: 'apple', translate: ''},
    {word: 'April', translate: ''}, {word: 'arm', translate: ''}, {word: 'as', translate: ''},
    {word: 'ask', translate: ''}, {word: 'at', translate: ''}, {word: 'August', translate: ''},
    {word: 'baby', translate: ''}, {word: 'back', translate: ''}, {word: 'bad', translate: ''},
    {word: 'bag', translate: ''}, {word: 'ball', translate: ''}, {word: 'banana', translate: ''},
    {word: 'band', translate: ''}, {word: 'bank', translate: ''}, {word: 'bar', translate: ''},
    {word: 'basketball', translate: ''}, {word: 'bath', translate: ''}, {word: 'bathroom', translate: ''},
    {word: 'be', translate: ''}, {word: 'beach', translate: ''}, {word: 'beard', translate: ''},
    {word: 'beautiful', translate: ''}, {word: 'because', translate: ''}, {word: 'bed', translate: ''},
    {word: 'bedroom', translate: ''}, {word: 'beer', translate: ''}, {word: 'before', translate: ''},
    {word: 'begin', translate: ''}, {word: 'behind', translate: ''}, {word: 'below', translate: ''},
    {word: 'best', translate: ''}, {word: 'better', translate: ''}, {word: 'between', translate: ''},
    {word: 'big', translate: ''}, {word: 'bird', translate: ''}, {word: 'birthday', translate: ''},
    {word: 'biscuit', translate: ''}, {word: 'black', translate: ''}, {word: 'blue', translate: ''},
    {word: 'board', translate: ''}, {word: 'boat', translate: ''}, {word: 'body', translate: ''},
    {word: 'book', translate: ''}, {word: 'bored', translate: ''}, {word: 'boring', translate: ''},
    {word: 'both', translate: ''}, {word: 'bottom', translate: ''}, {word: 'box', translate: ''},
    {word: 'boy', translate: ''}, {word: 'bread', translate: ''}, {word: 'breakfast', translate: ''},
    {word: 'brother', translate: ''}, {word: 'brown', translate: ''}, {word: 'bus', translate: ''},
    {word: 'business', translate: ''}, {word: 'but', translate: ''}, {word: 'butter', translate: ''},
    {word: 'buy', translate: ''}, {word: 'bye', translate: ''}, {word: 'cafe', translate: ''},
    {word: 'cake', translate: ''}, {word: 'call', translate: ''}, {word: 'camera', translate: ''},
    {word: 'can', translate: ''}, {word: 'cannot', translate: ''}, {word: 'car', translate: ''},
    {word: 'carry', translate: ''}, {word: 'cat', translate: ''}, {word: 'catch', translate: ''},
    {word: 'CD', translate: ''}, {word: 'CD player', translate: ''}, {word: 'chair', translate: ''},
    {word: 'change', translate: ''}, {word: 'cheap', translate: ''}, {word: 'cheese', translate: ''},
    {word: 'child', translate: ''}, {word: 'chip', translate: ''}, {word: 'chocolate', translate: ''},
    {word: 'choose', translate: ''}, {word: 'cinema', translate: ''}, {word: 'city', translate: ''},
    {word: 'class', translate: ''}, {word: 'classroom', translate: ''}, {word: 'clean', translate: ''},
    {word: 'clever', translate: ''}, {word: 'clock', translate: ''}, {word: 'close', translate: ''},
    {word: 'closed', translate: ''}, {word: 'clothes', translate: ''}, {word: 'coat', translate: ''},
    {word: 'coffee', translate: ''}, {word: 'cold', translate: ''}, {word: 'colour', translate: ''},
    {word: 'come', translate: ''}, {word: 'computer', translate: ''}, {word: 'conversation', translate: ''},
    {word: 'cook', translate: ''}, {word: 'country', translate: ''}, {word: 'course', translate: ''},
    {word: 'cow', translate: ''}, {word: 'credit card', translate: ''}, {word: 'cross', translate: ''},
    {word: 'cup', translate: ''}, {word: 'dad', translate: ''}, {word: 'dance', translate: ''},
    {word: 'dancing', translate: ''}, {word: 'dark', translate: ''}, {word: 'date', translate: ''},
    {word: 'daughter', translate: ''}, {word: 'day', translate: ''}, {word: 'dear', translate: ''},
    {word: 'December', translate: ''}, {word: 'desk', translate: ''}, {word: 'dictionary', translate: ''},
    {word: 'die', translate: ''}, {word: 'different', translate: ''}, {word: 'difficult', translate: ''},
    {word: 'dining room', translate: ''}, {word: 'dinner', translate: ''}, {word: 'do', translate: ''},
    {word: 'doctor', translate: ''}, {word: 'dog', translate: ''}, {word: 'doll', translate: ''},
    {word: 'dollar', translate: ''}, {word: 'door', translate: ''}, {word: 'dawn', translate: ''},
    {word: 'draw', translate: ''}, {word: 'dress', translate: ''}, {word: 'drink', translate: ''},
    {word: 'drive', translate: ''}, {word: 'driver', translate: ''}, {word: 'DVD', translate: ''},
    {word: '', translate: ''}, {word: '', translate: ''}, {word: '', translate: ''},
    {word: '', translate: ''}, {word: '', translate: ''}, {word: '', translate: ''},
    {word: '', translate: ''}, {word: '', translate: ''}, {word: '', translate: ''},
]