const A1_wordlist = [
    {word: 'about', translate: 'о'}, {word: 'above', translate: 'выше'}, {word: 'address', translate: 'адрес'},
    {word: 'adult', translate: 'взрослый'}, {word: 'after', translate: 'после'}, {word: 'afternoon', translate: 'полдень'},
    {word: 'again', translate: 'снова'}, {word: 'age', translate: 'возраст'}, {word: 'all', translate: 'все'},
    {word: 'all right', translate: 'все в порядке'}, {word: 'alright', translate: 'хорошо'}, {word: 'also', translate: 'также'},
    {word: 'always', translate: 'всегда'}, {word: 'a.m', translate: 'время в первой половине дня'}, {word: 'an', translate: '(предлог)'},
    {word: 'and', translate: 'и'}, {word: 'animal', translate: 'животное'}, {word: 'answer', translate: 'ответ'},
    {word: 'any', translate: 'любой'}, {word: 'anything', translate: 'что-либо'}, {word: 'apple', translate: 'яблоко'},
    {word: 'April', translate: 'Апрель'}, {word: 'arm', translate: 'рука'}, {word: 'as', translate: 'как'},
    {word: 'ask', translate: 'просить'}, {word: 'at', translate: '(предлог)'}, {word: 'August', translate: 'Август'},
    {word: 'baby', translate: 'младенец'}, {word: 'back', translate: 'назад'}, {word: 'bad', translate: 'плохой'},
    {word: 'bag', translate: 'рюкзак'}, {word: 'ball', translate: 'мяч'}, {word: 'banana', translate: 'банан'},
    {word: 'band', translate: 'группа'}, {word: 'bank', translate: 'банк'}, {word: 'bar', translate: 'бар'},
    {word: 'basketball', translate: 'баскетбол'}, {word: 'bath', translate: 'ванная'}, {word: 'bathroom', translate: 'ванная комната'},
    {word: 'be', translate: 'быть'}, {word: 'beach', translate: 'пляж'}, {word: 'beard', translate: 'борода'},
    {word: 'beautiful', translate: 'красивый'}, {word: 'because', translate: 'потому что'}, {word: 'bed', translate: 'кровать'},
    {word: 'bedroom', translate: 'спальная комната'}, {word: 'beer', translate: 'пиво'}, {word: 'before', translate: 'до'},
    {word: 'begin', translate: 'начать'}, {word: 'behind', translate: 'сзади'}, {word: 'below', translate: 'ниже'},
    {word: 'best', translate: 'лучший'}, {word: 'better', translate: 'лучше'}, {word: 'between', translate: 'между'},
    {word: 'big', translate: 'большой'}, {word: 'bird', translate: 'птица'}, {word: 'birthday', translate: 'день рождения'},
    {word: 'biscuit', translate: 'бисквит'}, {word: 'black', translate: 'черный'}, {word: 'blue', translate: 'синий'},
    {word: 'board', translate: 'доска'}, {word: 'boat', translate: 'лодка'}, {word: 'body', translate: 'тело'},
    {word: 'book', translate: 'книга'}, {word: 'bored', translate: 'скучающий'}, {word: 'boring', translate: 'скучный'},
    {word: 'both', translate: 'оба'}, {word: 'bottom', translate: 'дно'}, {word: 'box', translate: 'коробка'},
    {word: 'boy', translate: 'мальчик'}, {word: 'bread', translate: 'хлеб'}, {word: 'breakfast', translate: 'завтрак'},
    {word: 'brother', translate: 'брат'}, {word: 'brown', translate: 'коричневый'}, {word: 'bus', translate: 'автобус'},
    {word: 'business', translate: 'бизнес'}, {word: 'but', translate: 'но'}, {word: 'butter', translate: 'масло'},
    {word: 'buy', translate: 'купить'}, {word: 'bye', translate: 'пока'}, {word: 'cafe', translate: 'кафе'},
    {word: 'cake', translate: 'торт'}, {word: 'call', translate: 'позвонить'}, {word: 'camera', translate: 'камера'},
    {word: 'can', translate: 'может'}, {word: 'cannot', translate: 'не может'}, {word: 'car', translate: 'машина'},
    {word: 'carry', translate: 'нести'}, {word: 'cat', translate: 'кот'}, {word: 'catch', translate: 'ловить'},
    {word: 'CD', translate: 'компакт-диск'}, {word: 'CD player', translate: 'CD плеер'}, {word: 'chair', translate: 'стул'},
    {word: 'change', translate: 'изменять'}, {word: 'cheap', translate: 'дешёвый'}, {word: 'cheese', translate: 'сыр'},
    {word: 'child', translate: 'ребёнок'}, {word: 'chip', translate: 'чип'}, {word: 'chocolate', translate: 'шоколад'},
    {word: 'choose', translate: 'выбирать'}, {word: 'cinema', translate: 'кинотеатр'}, {word: 'city', translate: 'город'},
    {word: 'class', translate: 'класс'}, {word: 'classroom', translate: 'классная комната'}, {word: 'clean', translate: 'убирать'},
    {word: 'clever', translate: 'умный'}, {word: 'clock', translate: 'часы'}, {word: 'close', translate: 'закрывать'},
    {word: 'closed', translate: 'закрытый'}, {word: 'clothes', translate: 'одежда'}, {word: 'coat', translate: 'пальто'},
    {word: 'coffee', translate: 'кофе'}, {word: 'cold', translate: 'холодный'}, {word: 'colour', translate: 'цвет'},
    {word: 'come', translate: 'приходить'}, {word: 'computer', translate: 'компьютер'}, {word: 'conversation', translate: 'разговор'},
    {word: 'cook', translate: 'готовить'}, {word: 'country', translate: 'страна'}, {word: 'course', translate: 'курс'},
    {word: 'cow', translate: 'корова'}, {word: 'credit card', translate: 'кредитная карта'}, {word: 'cross', translate: 'крест'},
    {word: 'cup', translate: 'кружка'}, {word: 'dad', translate: 'отец'}, {word: 'dance', translate: 'танец'},
    {word: 'dancing', translate: 'танцы'}, {word: 'dark', translate: 'темный'}, {word: 'date', translate: 'свидание'},
    {word: 'daughter', translate: 'дочь'}, {word: 'day', translate: 'день'}, {word: 'dear', translate: 'дорогой'},
    {word: 'December', translate: 'Декабрь'}, {word: 'desk', translate: 'рабочий стол'}, {word: 'dictionary', translate: 'словарь'},
    {word: 'die', translate: 'умирать'}, {word: 'different', translate: 'разный'}, {word: 'difficult', translate: 'сложный'},
    {word: 'dining room', translate: 'столовая'}, {word: 'dinner', translate: 'ужин'}, {word: 'do', translate: 'делать'},
    {word: 'doctor', translate: 'доктор'}, {word: 'dog', translate: 'собака'}, {word: 'doll', translate: 'кукла'},
    {word: 'dollar', translate: 'доллар'}, {word: 'door', translate: 'дверь'}, {word: 'dawn', translate: 'рассвет'},
    {word: 'draw', translate: 'ничья'}, {word: 'dress', translate: 'платье'}, {word: 'drink', translate: 'пить'},
    {word: 'drive', translate: 'водить'}, {word: 'driver', translate: 'водитель'}, {word: 'DVD', translate: 'проигрыватель'},
    {word: 'each', translate: 'каждый'}, {word: 'ear', translate: 'ухо'}, {word: 'early', translate: 'рано'},
    {word: 'easy', translate: 'легкий'}, {word: 'eat', translate: 'кушать'}, {word: 'egg', translate: 'яйцо'},
    {word: 'eight', translate: 'восемь'}, {word: 'eighteen', translate: 'восемнадцать'}, {word: 'eleven', translate: 'одинадцать'},
    {word: 'email', translate: 'электронная почта'}, {word: 'end', translate: 'конец'}, {word: 'enjoy', translate: 'наслаждаться'},
    {word: 'evening', translate: 'вечер'}, {word: 'every', translate: 'каждый'}, {word: 'example', translate: 'пример'},
    {word: 'excited', translate: 'взволнованный'}, {word: 'exciting', translate: 'захватывающий'}, {word: 'excuse', translate: 'извинение'},
    {word: 'expensive', translate: 'дорогой'}, {word: 'eye', translate: 'глаз'}, {word: 'face', translate: 'лицо'},
    {word: 'factory', translate: 'завод'}, {word: 'family', translate: 'семья'}, {word: 'famous', translate: 'известный'},
    {word: 'farm', translate: 'ферма'}, {word: 'fast', translate: 'быстрый'}, {word: 'fat', translate: 'толстый'},
    {word: 'father', translate: 'отец'}, {word: 'favourite', translate: 'любимый'}, {word: 'February', translate: 'Февраль'},
    {word: 'feel', translate: 'чувство'}, {word: 'fifteen', translate: 'пятнадцать'}, {word: 'film', translate: 'фильм'},
    {word: 'find', translate: 'находить'}, {word: 'fine', translate: 'отлично'}, {word: 'finish', translate: 'заканчивать'},
    {word: 'first', translate: 'первый'}, {word: 'fish', translate: 'рыба'}, {word: 'five', translate: 'пять'},
    {word: 'flat', translate: 'квартира'}, {word: 'floor', translate: 'пол'}, {word: 'flower', translate: 'цветок'},
    {word: 'fly', translate: 'летать'}, {word: 'food', translate: 'еда'}, {word: 'foot', translate: 'нога'},
    {word: 'football', translate: 'футбол'}, {word: 'for', translate: 'для'}, {word: 'forget', translate: 'забыть'},
    {word: 'four', translate: 'четыре'}, {word: 'fourteen', translate: 'четырнадцать'}, {word: 'Friday', translate: 'Пятница'},
    {word: 'friend', translate: 'друг'}, {word: 'from', translate: 'от'}, {word: 'fruit', translate: 'фрукт'},
    {word: 'fun', translate: 'веселье'}, {word: 'funny', translate: 'веселый'}, {word: 'game', translate: 'игра'},
    {word: 'garden', translate: 'сад'}, {word: 'get', translate: 'получать'}, {word: 'girl', translate: 'девочка'},
    {word: 'give', translate: 'давать'}, {word: 'glass', translate: 'стекло'}, {word: 'glasses', translate: 'очки'},
    {word: 'go', translate: 'идти'}, {word: 'good', translate: 'хорошо'}, {word: 'good afternoon', translate: 'добрый день'},
    {word: 'goodbye', translate: 'пока'}, {word: 'good evening', translate: 'добрый вечер'}, {word: 'good morning', translate: 'доброе утро'},
    {word: 'good night', translate: 'доброй ночи'}, {word: 'grass', translate: 'трава'}, {word: 'great', translate: 'отличный'},
    {word: 'green', translate: 'зеленый'}, {word: 'grey', translate: 'серый'}, {word: 'group', translate: 'группа'},
    {word: 'guitar', translate: 'гитара'}, {word: 'hair', translate: 'волосы'}, {word: 'half', translate: 'половина'},
    {word: 'hand', translate: 'рука'}, {word: 'happy', translate: 'счатсливый'}, {word: 'hard', translate: 'тяжёлый'},
    {word: 'hat', translate: 'шапка'}, {word: 'have', translate: 'иметь'}, {word: 'he', translate: 'он'},
    {word: 'head', translate: 'голова'}, {word: 'hear', translate: 'слышать'}, {word: 'hello', translate: 'привет'},
    {word: 'help', translate: 'помощь'}, {word: 'her', translate: 'ей'}, {word: 'here', translate: 'здесь'},
    {word: 'hi', translate: 'привет'}, {word: 'him', translate: 'ему'}, {word: 'his', translate: 'его'},
    {word: 'holiday', translate: 'каникулы'}, {word: 'home', translate: 'дом'}, {word: 'homework', translate: 'домашняя работа'},
    {word: 'horse', translate: 'лошадь'}, {word: 'hospital', translate: 'больница'}, {word: 'hot', translate: 'горячий'},
    {word: 'hotel', translate: 'отель'}, {word: 'hour', translate: 'час'}, {word: 'house', translate: 'дом'},
    {word: 'how', translate: 'как'}, {word: 'hungry', translate: 'голодный'}, {word: 'husband', translate: 'муж'},
    {word: 'I', translate: 'я'}, {word: 'ice cream', translate: 'мороженное'}, {word: 'important', translate: 'важный'},
    {word: 'in', translate: 'в'}, {word: 'inside', translate: 'внутри'}, {word: 'interesting', translate: 'интересный'},
    {word: 'into', translate: 'в'}, {word: 'invite', translate: 'приглашать'}, {word: 'it', translate: 'это'},
    {word: 'its', translate: 'его'}, {word: 'jacket', translate: 'куртка'}, {word: 'January', translate: 'Январь'},
    {word: 'jeans', translate: 'джинсы'}, {word: 'job', translate: 'работа'}, {word: 'juice', translate: 'сок'},
    {word: 'July', translate: 'Июль'}, {word: 'June', translate: 'Июнь'}, {word: 'key', translate: 'ключ'},
    {word: 'kick', translate: 'пинать'}, {word: 'kind', translate: 'добрый'}, {word: 'kitchen', translate: 'кухня'},
    {word: 'knife', translate: 'нож'}, {word: 'know', translate: 'знать'}, {word: 'language', translate: 'язык'},
    {word: 'last', translate: 'последний'}, {word: 'late', translate: 'поздно'}, {word: 'later', translate: 'позже'},
    {word: 'learn', translate: 'изучать'}, {word: 'leave', translate: 'покидать'}, {word: 'leg', translate: 'нога'},
    {word: 'lesson', translate: 'урок'}, {word: 'letter', translate: 'письмо'}, {word: 'life', translate: 'жизнь'},
    {word: 'light', translate: 'свет'}, {word: 'like', translate: 'нравиться'}, {word: 'listen', translate: 'слушать'},
    {word: 'little', translate: 'маленький'}, {word: 'live', translate: 'жить'}, {word: 'living room', translate: 'гостинная'},
    {word: 'long', translate: 'длинный'}, {word: 'look', translate: 'смотреть'}, {word: 'lot', translate: 'много'},
    {word: 'love', translate: 'любовь'}, {word: 'lunch', translate: 'ланч'}, {word: 'make', translate: 'делать'},
    {word: 'man', translate: 'мужчина'}, {word: 'many', translate: 'много'}, {word: 'March', translate: 'Март'},
    {word: 'May', translate: 'Май'}, {word: 'me', translate: 'мне'}, {word: 'meal', translate: 'обед'},
    {word: 'meat', translate: 'мясо'}, {word: 'meet', translate: 'встретить'}, {word: 'message', translate: 'сообщение'},
    {word: 'milk', translate: 'молоко'}, {word: 'minute', translate: 'минута'}, {word: 'miss', translate: 'скучать'},
    {word: 'mobile', translate: 'мобильный'}, {word: 'mobile phone', translate: 'мобильный телефон'}, {word: 'Monday', translate: 'Понедельник'},
    {word: 'money', translate: 'деньги'}, {word: 'month', translate: 'месяц'}, {word: 'more', translate: 'больше'},
    {word: 'morning', translate: 'утро'}, {word: 'mother', translate: 'мать'}, {word: 'mouth', translate: 'рот'},
    {word: 'movie', translate: 'кино'}, {word: 'Mr', translate: 'мистер'}, {word: 'Mrs', translate: 'миссис'},
    {word: 'much', translate: 'много'}, {word: 'mum', translate: 'мама'}, {word: 'museum', translate: 'музей'},
    {word: 'music', translate: 'музыка'}, {word: 'my', translate: 'мой'}, {word: 'name', translate: 'имя'},
    {word: 'nationality', translate: 'национальность'}, {word: 'near', translate: 'рядом'}, {word: 'need', translate: 'нужно'},
    {word: 'never', translate: 'никогда'}, {word: 'new', translate: 'новый'}, {word: 'newspaper', translate: 'газета'},
    {word: 'next', translate: 'следующий'}, {word: 'nice', translate: 'крутой'}, {word: 'night', translate: 'ночь'},
    {word: 'nine', translate: 'девять'}, {word: 'nineteen', translate: 'девятнадцать'}, {word: 'no', translate: 'нет'},
    {word: 'noise', translate: 'шум'}, {word: 'nose', translate: 'нос'}, {word: 'not', translate: 'не'},
    {word: 'note', translate: 'заметка'}, {word: 'November', translate: 'Ноябрь'}, {word: 'now', translate: 'сейчас'},
    {word: 'number', translate: 'номер'}, {word: "o'clock", translate: 'час'}, {word: 'October', translate: 'Октябрь'},
    {word: 'of', translate: 'из'}, {word: 'often', translate: 'часто'}, {word: 'oh', translate: 'ой'},
    {word: 'Ok', translate: 'ок'}, {word: 'old', translate: 'старый'}, {word: 'on', translate: 'на'},
    {word: 'one', translate: 'один'}, {word: 'only', translate: 'только'}, {word: 'open', translate: 'открыть'},
    {word: 'or', translate: 'или'}, {word: 'orange', translate: 'оранжевый'}, {word: 'other', translate: 'другой'},
    {word: 'our', translate: 'наш'}, {word: 'outside', translate: 'снаружи'}, {word: 'page', translate: 'страница'},
    {word: 'paint', translate: 'краска'}, {word: 'pair', translate: 'пара'}, {word: 'paper', translate: 'бумага'},
    {word: 'parent', translate: 'родитель'}, {word: 'park', translate: 'парк'}, {word: 'part', translate: 'часть'},
    {word: 'party', translate: 'вечеринка'}, {word: 'past', translate: 'прошлый'}, {word: 'pay', translate: 'платить'},
    {word: 'pen', translate: 'ручка'}, {word: 'pencil', translate: 'карандаш'}, {word: 'people', translate: 'люди'},
    {word: 'person', translate: 'человек'}, {word: 'pet', translate: 'питомец'}, {word: 'phone', translate: 'телефон'},
    {word: 'photo', translate: 'фото'}, {word: 'picnic', translate: 'пикник'}, {word: 'picture', translate: 'изображение'},
    {word: 'pig', translate: 'свинья'}, {word: 'pizza', translate: 'пицца'}, {word: 'place', translate: 'место'},
    {word: 'plane', translate: 'самолет'}, {word: 'plant', translate: 'растение'}, {word: 'plate', translate: 'тарелка'},
    {word: 'play', translate: 'играть'}, {word: 'player', translate: 'игрок'}, {word: 'please', translate: 'пожалуйста'},
    {word: 'p.m.', translate: 'время второй половины дня'}, {word: 'poor', translate: 'бедный'}, {word: 'possible', translate: 'возможный'},
    {word: 'potato', translate: 'картошка'}, {word: 'practise', translate: 'практика'}, {word: 'present', translate: 'настоящий'},
    {word: 'problem', translate: 'проблема'}, {word: 'put', translate: 'класть'}, {word: 'quarter', translate: 'четверть'},
    {word: 'question', translate: 'вопрос'}, {word: 'quick', translate: 'быстрый'}, {word: 'radio', translate: 'радио'},
    {word: 'rain', translate: 'дождь'}, {word: 'read', translate: 'читать'}, {word: 'reading', translate: 'чтение'},
    {word: 'ready', translate: 'готовый'}, {word: 'really', translate: 'действительно'}, {word: 'red', translate: 'красный'},
    {word: 'remember', translate: 'помнить'}, {word: 'restaurant', translate: 'ресторан'}, {word: 'rice', translate: 'расти'},
    {word: 'ride', translate: 'поездка'}, {word: 'right', translate: 'право'}, {word: 'river', translate: 'речка'},
    {word: 'road', translate: 'дорого'}, {word: 'room', translate: 'комната'}, {word: 'run', translate: 'бегать'},
    {word: 'sad', translate: 'грустный'}, {word: 'safe', translate: 'безопасный'}, {word: 'salt', translate: 'соль'},
    {word: 'same', translate: 'такой же'}, {word: 'sandwich', translate: 'бутерброд'}, {word: 'Saturday', translate: 'Суббота'},
    {word: 'say', translate: 'сказать'}, {word: 'school', translate: 'школа'}, {word: 'sea', translate: 'море'},
    {word: 'second', translate: 'второй'}, {word: 'see', translate: 'видеть'}, {word: 'send', translate: 'отправить'},
    {word: 'sentence', translate: 'предложение'}, {word: 'September', translate: 'Сентябрь'}, {word: 'seven', translate: 'семь'},
    {word: 'seventeen', translate: 'семнадцать'}, {word: 'she', translate: 'она'}, {word: 'sheep', translate: 'овца'},
    {word: 'shirt', translate: 'рубашка'}, {word: 'shoe', translate: 'обувь'}, {word: 'shop', translate: 'магазин'},
    {word: 'shopping', translate: 'шоппинг'}, {word: 'short', translate: 'короткий'}, {word: 'show', translate: 'показывать'},
    {word: 'shower', translate: 'душ'}, {word: 'sing', translate: 'петь'}, {word: 'sister', translate: 'сестра'},
    {word: 'sit', translate: 'сидеть'}, {word: 'six', translate: 'шесть'}, {word: 'sixteen', translate: 'шестнадцать'},
    {word: 'skirt', translate: 'юбка'}, {word: 'sleep', translate: 'спать'}, {word: 'slim', translate: 'стройный'},
    {word: 'slow', translate: 'медленный'}, {word: 'small', translate: 'маленький'}, {word: 'smoke', translate: 'курить'},
    {word: 'smoking', translate: 'курящий'}, {word: 'snow', translate: 'снег'}, {word: 'some', translate: 'несколько'},
    {word: 'something', translate: 'что-то'}, {word: 'sometimes', translate: 'иногда'}, {word: 'son', translate: 'сын'},
    {word: 'soon', translate: 'скоро'}, {word: 'sorry', translate: 'извини'}, {word: 'soup', translate: 'суп'},
    {word: 'speak', translate: 'говорить'}, {word: 'sport', translate: 'спорт'}, {word: 'start', translate: 'старт'},
    {word: 'station', translate: 'станция'}, {word: 'stay', translate: 'стоять'}, {word: 'stop', translate: 'стоп'},
    {word: 'street', translate: 'улица'}, {word: 'student', translate: 'студент'}, {word: 'study', translate: 'учиться'},
    {word: 'subject', translate: 'предмет'}, {word: 'sugar', translate: 'сахар'}, {word: 'summer', translate: 'лето'},
    {word: 'sun', translate: 'солнце'}, {word: 'Sunday', translate: 'Воскресенье'}, {word: 'supermarket', translate: 'супермаркет'},
    {word: 'sweet', translate: 'сладкий'}, {word: 'swim', translate: 'плавать'}, {word: 'swimming pool', translate: 'бассейн'},
    {word: 'table', translate: 'стол'}, {word: 'take', translate: 'брать'}, {word: 'talk', translate: 'говорить'},
    {word: 'tall', translate: 'длинный'}, {word: 'taxi', translate: 'такси'}, {word: 'tea', translate: 'чай'},
    {word: 'teach', translate: 'обучать'}, {word: 'teacher', translate: 'учитель'}, {word: 'television', translate: 'телевидение'},
    {word: 'tell', translate: 'рассказывать'}, {word: 'ten', translate: 'десять'}, {word: 'tennis', translate: 'теннис'},
    {word: 'test', translate: 'тест'}, {word: 'than', translate: 'чем'}, {word: 'thanks', translate: 'спасибо'},
    {word: 'thank you', translate: 'спасибо'}, {word: 'that', translate: 'тот'}, {word: 'the', translate: 'это'},
    {word: 'the Internet', translate: 'интернет'}, {word: 'their', translate: 'их'}, {word: 'them', translate: 'им'},
    {word: 'then', translate: 'затем'}, {word: 'there', translate: 'там'}, {word: 'these', translate: 'эти'},
    {word: 'they', translate: 'они'}, {word: 'thing', translate: 'вещь'}, {word: 'think', translate: 'думать'},
    {word: 'thirteen', translate: 'тринадцать'}, {word: 'this', translate: 'этот'}, {word: 'those', translate: 'тот'},
    {word: 'three', translate: 'три'}, {word: 'Thursday', translate: 'Четверг'}, {word: 'ticket', translate: 'билет'},
    {word: 'time', translate: 'время'}, {word: 'tired', translate: 'уставший'}, {word: 'to', translate: 'к'},
    {word: 'today', translate: 'сегодня'}, {word: 'together', translate: 'вместе'}, {word: 'toilet', translate: 'туалет'},
    {word: 'tomato', translate: 'помидор'}, {word: 'tomorrow', translate: 'завтра'}, {word: 'tonight', translate: 'ночью'},
    {word: 'too', translate: 'тоже'}, {word: 'tooth', translate: 'зубы'}, {word: 'town', translate: 'город'},
    {word: 'train', translate: 'поезд'}, {word: 'travel', translate: 'путешествовать'}, {word: 'tree', translate: 'дерево'},
    {word: 'trousers', translate: 'штаны'}, {word: 'T-shirt', translate: 'футболка'}, {word: 'Tuesday', translate: 'Вторник'},
    {word: 'TV', translate: 'телевизор'}, {word: 'twelve', translate: 'двенадцать'}, {word: 'twenty', translate: 'двадцать'},
    {word: 'two', translate: 'два'}, {word: 'under', translate: 'под'}, {word: 'understand', translate: 'понимать'},
    {word: 'university', translate: 'университет'}, {word: 'until', translate: 'до'}, {word: 'up', translate: 'вверх'},
    {word: 'us', translate: 'нас'}, {word: 'use', translate: 'использовать'}, {word: 'vegetable', translate: 'овощи'},
    {word: 'very', translate: 'очень'}, {word: 'village', translate: 'деревня'}, {word: 'visit', translate: 'посещать'},
    {word: 'wait', translate: 'ждать'}, {word: 'waiter', translate: 'официант'}, {word: 'waitress', translate: 'официантка'},
    {word: 'wake', translate: 'просыпаться'}, {word: 'walk', translate: 'гулять'}, {word: 'wall', translate: 'стена'},
    {word: 'want', translate: 'хотеть'}, {word: 'warm', translate: 'теплый'}, {word: 'wash', translate: 'стирать'},
    {word: 'watch', translate: 'смотреть'}, {word: 'water', translate: 'вода'}, {word: 'we', translate: 'мы'},
    {word: 'wear', translate: 'носить'}, {word: 'weather', translate: 'погода'}, {word: 'website', translate: 'вебсайт'},
    {word: 'Wednesday', translate: 'Среда'}, {word: 'week', translate: 'неделя'}, {word: 'weekend', translate: 'выходной'},
    {word: 'well', translate: 'хорошо'}, {word: 'what', translate: 'что'}, {word: 'when', translate: 'когда'},
    {word: 'where', translate: 'где'}, {word: 'which', translate: 'какой'}, {word: 'white', translate: 'белый'},
    {word: 'who', translate: 'кто'}, {word: 'why', translate: 'почему'}, {word: 'wife', translate: 'жена'},
    {word: 'will', translate: 'будет'}, {word: 'wind', translate: 'ветер'}, {word: 'window', translate: 'окно'},
    {word: 'wine', translate: 'вино'}, {word: 'winter', translate: 'зима'}, {word: 'with', translate: 'с'},
    {word: 'woman', translate: 'женщина'}, {word: 'word', translate: 'слово'}, {word: 'work', translate: 'работа'},
    {word: 'world', translate: 'мир'}, {word: 'worry', translate: 'волноваться'}, {word: 'would', translate: 'бы'},
    {word: 'write', translate: 'писать'}, {word: 'writing', translate: 'писание'}, {word: 'wrong', translate: 'неправильный'},
    {word: 'year', translate: 'год'}, {word: 'yellow', translate: 'желтый'}, {word: 'yes', translate: 'да'},
    {word: 'yesterday', translate: 'вчера'}, {word: 'you', translate: 'ты'}, {word: 'young', translate: 'молодой'},
    {word: 'your', translate: 'твой'}, {word: 'zoo', translate: 'зоопарк'},
]

module.exports = {
    A1_wordlist
}